language: python
sudo: false

matrix:
  include:
    # Flake8 Style Checking
    - python: 3.6
      env: TOXENV=flake8

    # Docs
    - python: 3.6
      env: TOXENV=docs

    # Linux Builds
    - python: 3.6
      env: TOXENV=py36
    - python: nightly
      env: TOXENV=py37

    # OSX Builds
    - language: generic
      os: osx
      env: TOXENV=py36

cache:
  - pip
  - directories:
    - ${HOME}/.cache

install:
  - chmod a+x ./.travis/install.sh ./.travis/run.sh ./.travis/upload_coverage.sh
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

after_success:
  - ./.travis/upload_coverage.sh

notifications:
  email: false

branches:
  only:
  - master
  - release
